<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net35</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="IllusionModdingAPI.KKAPI" Version="1.36.0" />
		<PackageReference Include="ScreenshotManager.Koikatu" Version="19.3.3" />
	</ItemGroup>

	<Import Project="..\Core_Fix_Eyebrows\Core_Fix_Eyebrows.projitems" Label="Shared" />
	<Import Project="..\Common\Common.projitems" Label="Shared" />
</Project>