<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net35</TargetFramework>
		<DefineConstants>$(DefineConstants);KK</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Update="KoikatuCompatibilityAnalyzer">
			<ExcludeAssets>all</ExcludeAssets>
		</PackageReference>
		<!-- This is necessary to override the Koikatu dll added by AllPackages with the dll in KoikatsuParty package (dll from AllPackages takes priority by default) -->
		<PackageReference Include="IllusionLibs.Koikatu.Assembly-CSharp" Version="2019.4.27.*">
			<ExcludeAssets>all</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="IllusionLibs.KoikatsuParty.Assembly-CSharp" Version="2021.3.25" />
	</ItemGroup>

	<Import Project="..\Common\Common.projitems" Label="Shared" />
</Project>