<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net35</TargetFramework>
		<AssemblyName>KK_Fix_InvalidSceneFileProtection</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Update="ExtensibleSaveFormat.KoikatsuSunshine">
			<ExcludeAssets>all</ExcludeAssets>
		</PackageReference>
		<PackageReference Update="IllusionLibs.KoikatsuSunshine.AllPackages">
			<ExcludeAssets>all</ExcludeAssets>
		</PackageReference>
	</ItemGroup>

	<Target Name="CopyOutputDll" AfterTargets="Build">
		<Copy SourceFiles="$(TargetPath)" DestinationFiles="$(TargetDir)KKS_Fix_InvalidSceneFileProtection.dll" />
	</Target>

	<Import Project="..\Core_Fix_InvalidSceneFileProtection\Core_Fix_InvalidSceneFileProtection.projitems" Label="Shared" />
	<Import Project="..\Common\Common.projitems" Label="Shared" />
</Project>