<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net46</TargetFramework>
		<AssemblyName>AI_Fix_DynamicBones</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Update="ExtensibleSaveFormat.HoneySelect2">
			<ExcludeAssets>all</ExcludeAssets>
		</PackageReference>
		<PackageReference Update="IllusionLibs.HoneySelect2.AllPackages">
			<ExcludeAssets>all</ExcludeAssets>
		</PackageReference>
	</ItemGroup>

	<Target Name="CopyOutputDll" AfterTargets="Build">
		<Copy SourceFiles="$(TargetPath)" DestinationFiles="$(TargetDir)HS2_Fix_DynamicBones.dll" />
	</Target>

	<Import Project="..\Core_Fix_DynamicBones\Core_Fix_DynamicBones.projitems" Label="Shared" />
	<Import Project="..\Common\Common.projitems" Label="Shared" />
</Project>