<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net35</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="CalendarIcon\action_icon_calendar_off.png" />
		<EmbeddedResource Include="CalendarIcon\action_icon_calendar_on.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="IllusionModdingAPI.KKAPI" Version="1.36.0" />
	</ItemGroup>

	<Import Project="..\Common\Common.projitems" Label="Shared" />
</Project>