<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net46</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\setup.xml"/>
	</ItemGroup>

	<Import Project="..\Core_Fix_SettingsVerifier\Core_Fix_SettingsVerifier.projitems" Label="Shared" />
	<Import Project="..\Common\Common.projitems" Label="Shared" />
</Project>