<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net35</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="IllusionLibs.BepInEx.MonoMod" Version="22.1.29.1" />
	</ItemGroup>

	<Import Project="..\Core_Fix_ResourceUnloadOptimizations\Core_Fix_ResourceUnloadOptimizations.projitems" Label="Shared" />
	<Import Project="..\Common\Common.projitems" Label="Shared" />
</Project>