<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net46</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="IllusionModdingAPI.AIAPI" Version="1.36.0" />
	</ItemGroup>

	<Import Project="..\Core_Fix_MakerMaleFaceTypes\Core_Fix_MakerMaleFaceTypes.projitems" Label="Shared" />
	<Import Project="..\Common\Common.projitems" Label="Shared" />
</Project>